# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0005_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Image_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
